export type CampaignSnapshot = {
  id: string | number;
  name: string;
  platform: 'Google' | 'Meta' | 'TikTok';
  status: 'Active' | 'Paused';
  spend: number;
  roas: number;
};

export type CampaignSummary = {
  totalCampaigns: number;
  activeCampaigns: number;
  totalSpend: number;
  avgRoas: number;
  platformBreakdown: Array<{ platform: 'Google' | 'Meta' | 'TikTok'; count: number }>;
};

export type PlatformRevenueSummary = {
  meta: { spend: number; attributedRevenue: number };
  google: { spend: number; attributedRevenue: number };
  tiktok: { spend: number; attributedRevenue: number };
};

export type Ga4TopPage = {
  path: string;
  title: string;
  views: number;
};

export const STATUS_LABELS = {
  he: {
    completed: 'הושלמה',
    processing: 'בטיפול',
    pending: 'ממתינה',
    'on-hold': 'בהמתנה',
    cancelled: 'בוטלה',
    refunded: 'הוחזרה',
    failed: 'נכשלה',
  },
  en: {
    completed: 'Completed',
    processing: 'Processing',
    pending: 'Pending',
    'on-hold': 'On hold',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    failed: 'Failed',
  },
  ru: {
    completed: 'Завершен',
    processing: 'В обработке',
    pending: 'Ожидает',
    'on-hold': 'На удержании',
    cancelled: 'Отменен',
    refunded: 'Возврат',
    failed: 'Ошибка',
  },
  pt: {
    completed: 'Concluído',
    processing: 'Processando',
    pending: 'Pendente',
    'on-hold': 'Em espera',
    cancelled: 'Cancelado',
    refunded: 'Reembolsado',
    failed: 'Falhou',
  },
  fr: {
    completed: 'Terminée',
    processing: 'En cours',
    pending: 'En attente',
    'on-hold': 'En pause',
    cancelled: 'Annulée',
    refunded: 'Remboursée',
    failed: 'Échouée',
  },
} as const;

export const COPY = {
  he: {
    title: 'סקירה כללית',
    subtitle: 'נתונים מרכזיים מהחנות, מהקמפיינים, מ GA4 ומ Search Console במקום אחד.',
    syncing: 'מסנכרן נתונים חיים...',
    sourceLive: 'Live',
    sourceMissing: 'Missing metric',
    revenueCard: 'הכנסות',
    totalRevenue: 'סה"כ הכנסות',
    totalSpend: 'סה"כ הוצאות פרסום',
    metaSpend: 'הוצאות Meta',
    metaRevenue: 'הכנסה מיוחסת Meta',
    metaRevenueTooltip:
      'מחושב כסכום conversion value שהוחזר ממסעות Meta בטווח התאריכים. זהו נתון ייחוס פרסומי (attribution) והוא יכול להיות שונה מהכנסות WooCommerce בפועל.',
    netProfit: 'רווח נקי',
    roas: 'ROAS',
    noFinanceData: 'עדיין אין נתונים חיים להכנסות או הוצאות פרסום לטווח התאריכים שנבחר.',
    goOrders: 'מעבר לרשימת הזמנות',
    ga4Card: 'מצב גולשים באתר',
    ga4LiveSync: 'Live Sync · 30 דק\' אחרונות',
    activeNow: 'פעילים עכשיו',
    totalUsers: 'משתמשים ב-24 שעות אחרונות',
    topPagesLabel: 'עמודים פעילים כרגע (30 דק\' אחרונות)',
    ga4Desc: 'חלון חי בלבד: מציג גולשים פעילים עכשיו, משתמשים ב-24 שעות האחרונות, ועמודים פעילים ב-30 הדקות האחרונות — ללא קשר לטווח התאריכים שנבחר.',
    noGa4: 'אין כרגע נתוני GA4 חיים להצגה.',
    latestOrdersCard: '5 הזמנות אחרונות',
    customerFallback: 'לקוח',
    noOrders: 'אין כרגע נתוני הזמנות חיים להצגה.',
    goOrdersShort: 'מעבר להזמנות',
    campaignsCard: 'מצב קמפיינים מהפלטפורמות',
    totalCampaigns: 'סה"כ קמפיינים',
    activeCampaigns: 'פעילים כרגע',
    totalCampaignSpend: 'הוצאה כוללת',
    roasRos: 'ROAS / ROS',
    noCampaigns: 'אין כרגע נתוני קמפיינים חיים להצגה.',
    goCampaigns: 'מעבר לקמפיינים',
    seoCard: 'מצב SEO באתר מול Search Console',
    siteSeo: 'SEO באתר',
    scSeo: 'SEO ב Search Console',
    clicks: 'קליקים',
    impressions: 'חשיפות',
    ctr: 'CTR',
    avgPosition: 'מיקום ממוצע',
    noSeo: 'אין כרגע נתוני SEO חיים להצגה.',
    goSeo: 'מעבר ל SEO',
    optimizationCard: 'המלצות לאופטימיזציה',
    noFreshRecs: 'יש כרגע מעט נתונים חיים ולכן אין המלצות חדשות לאופטימיזציה.',
    noRecsData: 'אין כרגע מספיק נתונים חיים כדי ליצור המלצות אופטימיזציה.',
    aiRecs: 'המלצות AI',
    campaignOptimization: 'אופטימיזציית קמפיינים',
    recLowRoas: 'להגדיל תקציב רק בקמפיינים עם המרות בפועל ולעצור קבוצות מודעות חלשות.',
    recSeoStructure: 'לחזק SEO בדפי קטגוריה ומוצר עם כותרות H1 מדויקות וקישורים פנימיים.',
    recMetaCtr: 'לשפר Meta Title ו Meta Description בדפים עם חשיפות גבוהות ו CTR נמוך.',
    recFunnel: 'לבדוק משפך רכישה ועמודי Checkout כדי לשפר יחס המרה מתנועה להזמנה.',
    recPausedCampaigns: 'להפעיל מחדש רק קמפיינים מושהים עם עלות לרכישה יציבה וללא שחיקת ROAS.',
  },
  en: {
    title: 'Overview',
    subtitle: 'Key store, campaign, GA4 and Search Console data in one place.',
    syncing: 'Syncing live data...',
    sourceLive: 'Live',
    sourceMissing: 'Missing metric',
    revenueCard: 'Revenue',
    totalRevenue: 'Total revenue',
    totalSpend: 'Total ad spend',
    metaSpend: 'Meta spend',
    metaRevenue: 'Meta attributed revenue',
    metaRevenueTooltip:
      'Calculated as the sum of Meta campaign conversion value in the selected date range. This is an attribution metric and can differ from actual WooCommerce revenue.',
    netProfit: 'Net profit',
    roas: 'ROAS',
    noFinanceData: 'No live revenue or ad spend data for the selected date range yet.',
    goOrders: 'Go to orders list',
    ga4Card: 'Website traffic status (GA4)',
    ga4LiveSync: 'Live Sync · last 30 min',
    activeNow: 'Active now',
    totalUsers: 'Users in last 24 hours',
    topPagesLabel: 'Active pages now (last 30 min)',
    ga4Desc: 'Live window only: shows active users now, users in last 24h, and active pages in last 30 min — independent of the selected date range.',
    noGa4: 'No live GA4 data to display right now.',
    latestOrdersCard: 'Latest 5 orders',
    customerFallback: 'Customer',
    noOrders: 'No live order data to display right now.',
    goOrdersShort: 'Go to orders',
    campaignsCard: 'Campaign status across platforms',
    totalCampaigns: 'Total campaigns',
    activeCampaigns: 'Currently active',
    totalCampaignSpend: 'Total spend',
    roasRos: 'ROAS / ROS',
    noCampaigns: 'No live campaign data to display right now.',
    goCampaigns: 'Go to campaigns',
    seoCard: 'Website SEO vs Search Console',
    siteSeo: 'On-site SEO',
    scSeo: 'Search Console SEO',
    clicks: 'Clicks',
    impressions: 'Impressions',
    ctr: 'CTR',
    avgPosition: 'Avg position',
    noSeo: 'No live SEO data to display right now.',
    goSeo: 'Go to SEO',
    optimizationCard: 'Optimization recommendations',
    noFreshRecs: 'Live data is currently partial, so there are no new optimization recommendations.',
    noRecsData: 'Not enough live data yet to generate optimization recommendations.',
    aiRecs: 'AI recommendations',
    campaignOptimization: 'Campaign optimization',
    recLowRoas: 'Increase budget only for campaigns with real conversions and pause weak ad groups.',
    recSeoStructure: 'Strengthen category and product SEO with precise H1 titles and internal links.',
    recMetaCtr: 'Improve meta titles and descriptions on high impression pages with low CTR.',
    recFunnel: 'Review checkout and conversion funnel to improve traffic to order conversion rate.',
    recPausedCampaigns: 'Reactivate paused campaigns only when CPA is stable and ROAS is not eroding.',
  },
  ru: {
    title: 'Обзор',
    subtitle: 'Ключевые данные магазина, кампаний, GA4 и Search Console в одном месте.',
    syncing: 'Синхронизация live данных...',
    sourceLive: 'Live',
    sourceMissing: 'Missing metric',
    revenueCard: 'Доход',
    totalRevenue: 'Общий доход',
    totalSpend: 'Расходы на рекламу',
    metaSpend: 'Расходы Meta',
    metaRevenue: 'Доход, атрибутированный Meta',
    metaRevenueTooltip:
      'Рассчитывается как сумма conversion value из кампаний Meta за выбранный период. Это атрибуционная метрика и она может отличаться от фактической выручки WooCommerce.',
    netProfit: 'Чистая прибыль',
    roas: 'ROAS',
    noFinanceData: 'Пока нет live данных по доходу или расходам за выбранный период.',
    goOrders: 'Перейти к списку заказов',
    ga4Card: 'Состояние трафика сайта (GA4)',
    ga4LiveSync: 'Live Sync · последние 30 мин',
    activeNow: 'Сейчас активны',
    totalUsers: 'Пользователи за последние 24 часа',
    topPagesLabel: 'Активные страницы сейчас (30 мин)',
    ga4Desc: 'Только live-окно: активные пользователи сейчас, пользователи за 24 часа и активные страницы за 30 минут — не зависит от выбранного диапазона дат.',
    noGa4: 'Сейчас нет live данных GA4.',
    latestOrdersCard: 'Последние 5 заказов',
    customerFallback: 'Клиент',
    noOrders: 'Сейчас нет live данных заказов.',
    goOrdersShort: 'К заказам',
    campaignsCard: 'Состояние кампаний по платформам',
    totalCampaigns: 'Всего кампаний',
    activeCampaigns: 'Активных сейчас',
    totalCampaignSpend: 'Общие расходы',
    roasRos: 'ROAS / ROS',
    noCampaigns: 'Сейчас нет live данных по кампаниям.',
    goCampaigns: 'К кампаниям',
    seoCard: 'SEO сайта vs Search Console',
    siteSeo: 'SEO на сайте',
    scSeo: 'SEO Search Console',
    clicks: 'Клики',
    impressions: 'Показы',
    ctr: 'CTR',
    avgPosition: 'Средняя позиция',
    noSeo: 'Сейчас нет live SEO данных.',
    goSeo: 'К SEO',
    optimizationCard: 'Рекомендации по оптимизации',
    noFreshRecs: 'Сейчас мало live данных, поэтому новых рекомендаций нет.',
    noRecsData: 'Недостаточно live данных для рекомендаций.',
    aiRecs: 'AI рекомендации',
    campaignOptimization: 'Оптимизация кампаний',
    recLowRoas: 'Увеличивайте бюджет только для кампаний с реальными конверсиями.',
    recSeoStructure: 'Усильте SEO категорий и товаров с точными H1 и внутренними ссылками.',
    recMetaCtr: 'Улучшите meta title и description на страницах с высоким показом и низким CTR.',
    recFunnel: 'Проверьте воронку и checkout для повышения конверсии.',
    recPausedCampaigns: 'Возобновляйте только кампании со стабильной стоимостью привлечения.',
  },
  pt: {
    title: 'Visão geral',
    subtitle: 'Dados principais da loja, campanhas, GA4 e Search Console em um só lugar.',
    syncing: 'Sincronizando dados ao vivo...',
    sourceLive: 'Live',
    sourceMissing: 'Missing metric',
    revenueCard: 'Receita',
    totalRevenue: 'Receita total',
    totalSpend: 'Gasto total em anúncios',
    metaSpend: 'Gasto Meta',
    metaRevenue: 'Receita atribuída ao Meta',
    metaRevenueTooltip:
      'Calculada como a soma do conversion value das campanhas Meta no período selecionado. É uma métrica de atribuição e pode diferir da receita real do WooCommerce.',
    netProfit: 'Lucro líquido',
    roas: 'ROAS',
    noFinanceData: 'Ainda não há dados ao vivo de receita ou gasto no período selecionado.',
    goOrders: 'Ir para lista de pedidos',
    ga4Card: 'Status de tráfego do site (GA4)',
    ga4LiveSync: 'Live Sync · últimos 30 min',
    activeNow: 'Ativos agora',
    totalUsers: 'Usuários nas últimas 24 horas',
    topPagesLabel: 'Páginas ativas agora (30 min)',
    ga4Desc: 'Janela ao vivo apenas: usuários ativos agora, usuários em 24h e páginas ativas nos últimos 30 min — independente do período selecionado.',
    noGa4: 'Não há dados GA4 ao vivo para mostrar no momento.',
    latestOrdersCard: '5 pedidos mais recentes',
    customerFallback: 'Cliente',
    noOrders: 'Não há dados de pedidos ao vivo para mostrar no momento.',
    goOrdersShort: 'Ir para pedidos',
    campaignsCard: 'Status de campanhas por plataforma',
    totalCampaigns: 'Total de campanhas',
    activeCampaigns: 'Ativas agora',
    totalCampaignSpend: 'Gasto total',
    roasRos: 'ROAS / ROS',
    noCampaigns: 'Não há dados de campanhas ao vivo para mostrar no momento.',
    goCampaigns: 'Ir para campanhas',
    seoCard: 'SEO do site vs Search Console',
    siteSeo: 'SEO no site',
    scSeo: 'SEO no Search Console',
    clicks: 'Cliques',
    impressions: 'Impressões',
    ctr: 'CTR',
    avgPosition: 'Posição média',
    noSeo: 'Não há dados SEO ao vivo para mostrar no momento.',
    goSeo: 'Ir para SEO',
    optimizationCard: 'Recomendações de otimização',
    noFreshRecs: 'Há poucos dados ao vivo no momento, sem novas recomendações.',
    noRecsData: 'Dados ao vivo insuficientes para gerar recomendações.',
    aiRecs: 'Recomendações AI',
    campaignOptimization: 'Otimização de campanhas',
    recLowRoas: 'Aumente orçamento apenas em campanhas com conversões reais.',
    recSeoStructure: 'Reforce SEO de categorias e produtos com H1 correto e links internos.',
    recMetaCtr: 'Melhore meta title e description em páginas com alta impressão e CTR baixo.',
    recFunnel: 'Revise checkout e funil para melhorar conversão de tráfego em pedido.',
    recPausedCampaigns: 'Reative campanhas pausadas apenas com CPA estável e sem erosão de ROAS.',
  },
  fr: {
    title: 'Vue d\u2019ensemble',
    subtitle: 'Données clés de la boutique, des campagnes, de GA4 et de Search Console au même endroit.',
    syncing: 'Synchronisation des données en direct...',
    sourceLive: 'Live',
    sourceMissing: 'Missing metric',
    revenueCard: 'Revenus',
    totalRevenue: 'Revenu total',
    totalSpend: 'Dépenses publicitaires',
    metaSpend: 'Dépense Meta',
    metaRevenue: 'Revenu attribué à Meta',
    metaRevenueTooltip:
      'Calculé comme la somme de la conversion value des campagnes Meta sur la période sélectionnée. Il s\u2019agit d\u2019une métrique d\u2019attribution, pouvant différer du revenu WooCommerce réel.',
    netProfit: 'Bénéfice net',
    roas: 'ROAS',
    noFinanceData: 'Aucune donnée en direct de revenu ou de dépense pour la période sélectionnée.',
    goOrders: 'Aller à la liste des commandes',
    ga4Card: 'Statut du trafic du site (GA4)',
    ga4LiveSync: 'Live Sync · 30 dernières min',
    activeNow: 'Actifs maintenant',
    totalUsers: 'Utilisateurs des 24 dernières heures',
    topPagesLabel: 'Pages actives maintenant (30 dernières min)',
    ga4Desc: 'Fenêtre live uniquement : utilisateurs actifs maintenant, utilisateurs sur 24h et pages actives sur 30 min — indépendant de la plage de dates sélectionnée.',
    noGa4: 'Aucune donnée GA4 en direct à afficher pour le moment.',
    latestOrdersCard: '5 dernières commandes',
    customerFallback: 'Client',
    noOrders: 'Aucune donnée de commande en direct à afficher pour le moment.',
    goOrdersShort: 'Aller aux commandes',
    campaignsCard: 'Statut des campagnes par plateforme',
    totalCampaigns: 'Total campagnes',
    activeCampaigns: 'Actives actuellement',
    totalCampaignSpend: 'Dépense totale',
    roasRos: 'ROAS / ROS',
    noCampaigns: 'Aucune donnée campagne en direct à afficher pour le moment.',
    goCampaigns: 'Aller aux campagnes',
    seoCard: 'SEO du site vs Search Console',
    siteSeo: 'SEO du site',
    scSeo: 'SEO Search Console',
    clicks: 'Clics',
    impressions: 'Impressions',
    ctr: 'CTR',
    avgPosition: 'Position moyenne',
    noSeo: 'Aucune donnée SEO en direct à afficher pour le moment.',
    goSeo: 'Aller au SEO',
    optimizationCard: 'Recommandations d\u2019optimisation',
    noFreshRecs: 'Les données en direct sont partielles, pas de nouvelles recommandations.',
    noRecsData: 'Pas assez de données en direct pour générer des recommandations.',
    aiRecs: 'Recommandations AI',
    campaignOptimization: 'Optimisation des campagnes',
    recLowRoas: 'Augmenter le budget uniquement sur les campagnes avec de vraies conversions.',
    recSeoStructure: 'Renforcer le SEO des catégories et produits avec des H1 précis et des liens internes.',
    recMetaCtr: 'Améliorer les meta title et descriptions sur les pages à forte impression et faible CTR.',
    recFunnel: 'Analyser le checkout et l\u2019entonnoir pour améliorer la conversion.',
    recPausedCampaigns: 'Réactiver seulement les campagnes en pause avec un CPA stable.',
  },
} as const;

export type CopyText = typeof COPY[keyof typeof COPY];
